# Generated by Django 3.2.8 on 2021-10-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MegaRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('volume_gb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MegaUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mega_users.megarate')),
            ],
        ),
    ]
