# Generated by Django 3.2.8 on 2021-10-28 04:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mega_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaBinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, upload_to='bin/')),
            ],
        ),
        migrations.CreateModel(
            name='MegaFile',
            fields=[
                ('id', models.CharField(default=uuid.UUID('a194dfef-d5e9-4440-a21c-54ea050a7c9d'), max_length=255, primary_key=True, serialize=False)),
                ('binary', models.FileField(blank=True, upload_to='uploads/')),
                ('fileName', models.CharField(max_length=239)),
                ('serverFileName', models.CharField(default=128251471011771787438160196662461808322, max_length=239)),
                ('extension', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('preview', models.CharField(blank=True, default=None, max_length=512)),
                ('uploadUrl', models.CharField(blank=True, default=None, max_length=512)),
                ('downloadUrl', models.CharField(blank=True, default=None, max_length=512)),
                ('addDate', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='mega_users.megauser')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mega_files.megafile')),
            ],
        ),
    ]
