# Generated by Django 3.2.8 on 2021-10-28 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mega_files', '0002_auto_20211028_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megafile',
            name='id',
            field=models.CharField(default=uuid.UUID('3e0cb976-6cec-492e-ab42-5d768ec8bb37'), max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='megafile',
            name='serverFileName',
            field=models.CharField(default=210123395525052819075843026401847832348, max_length=239),
        ),
    ]
