# Generated by Django 3.2.8 on 2021-10-28 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mega_files', '0003_auto_20211028_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megafile',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='megafile',
            name='serverFileName',
            field=models.CharField(default=255714852281031103404202728585866345730, max_length=239),
        ),
    ]
