# Generated by Django 3.2.8 on 2021-10-28 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mega_files', '0004_auto_20211028_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='megafile',
            name='downloadUrlExpireDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='megafile',
            name='downloadUrl',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='megafile',
            name='preview',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='megafile',
            name='serverFileName',
            field=models.CharField(default=194601994957945151502227062720991977036, max_length=239),
        ),
        migrations.AlterField(
            model_name='megafile',
            name='uploadUrl',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
