# Generated by Django 3.2.8 on 2021-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_files', '0005_auto_20211028_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='megafile',
            name='serverFileName',
            field=models.CharField(default=89407535721875039822459319661375911690, max_length=239),
        ),
    ]
